export type BistCompany = {
  symbol: string;
  name: string;
  nameEn?: string;
  nameTr?: string;
  officialNameTr?: string;
  aliases?: string[];
  logoUrl?: string;
};

const BIST_LOGO_BASE_URL =
  "https://cdn.jsdelivr.net/gh/ahmeterenodaci/Istanbul-Stock-Exchange--BIST--including-symbols-and-logos/logos";

const RAW_BIST100_COMPANIES: Array<{ symbol: string; name: string }> = [
  { symbol: "AGHOL", name: "AG ANADOLU GROUP HOLDING" },
  { symbol: "AKBNK", name: "AKBANK" },
  { symbol: "AKSA", name: "AKSA ACRYLIC CHEMICAL INDUSTRY" },
  { symbol: "AKSEN", name: "AKSA ENERGY PRODUCTION" },
  { symbol: "ALARK", name: "ALARKO HOLDING" },
  { symbol: "ALTNY", name: "ALTINAY DEFENSE TECHNOLOGIES" },
  { symbol: "ANSGR", name: "ANADOLU INSURANCE COMPANY" },
  { symbol: "AEFES", name: "ANADOLU EFES BREWERY AND MALT INDUSTRY" },
  { symbol: "ARCLK", name: "ARCELIK" },
  { symbol: "ASELS", name: "ASELSAN ELECTRONICS INDUSTRY AND TRADE" },
  { symbol: "ASTOR", name: "ASTOR ENERGY" },
  { symbol: "BALSU", name: "BALSU FOOD INDUSTRY AND TRADE" },
  { symbol: "BTCIM", name: "BATICIM WEST ANATOLIA CEMENT INDUSTRY" },
  { symbol: "BSOKE", name: "BATISOKE SOKE CIMENTO INDUSTRY" },
  { symbol: "BIMAS", name: "BIM UNITED STORES" },
  { symbol: "BRSAN", name: "BORUSAN MANNESMANN PIPE INC." },
  { symbol: "BRYAT", name: "BORUSAN INVESTMENT AND MARKETING" },
  { symbol: "CCOLA", name: "COCA-COLA ICECEK" },
  { symbol: "CWENE", name: "CW ENERGY ENGINEERING TRADE AND INDUSTRY" },
  { symbol: "CANTE", name: "CAN2 THERMAL" },
  { symbol: "CIMSA", name: "CIMSA CEMENT INDUSTRY AND TRADE" },
  { symbol: "DOHOL", name: "DOGAN GROUP OF COMPANIES HOLDING" },
  { symbol: "DOAS", name: "DOGUS AUTOMOTIVE SERVICE AND TRADE" },
  { symbol: "DSTKF", name: "DESTEK FINANS FACTORING" },
  { symbol: "EFOR", name: "EFOR INVESTMENT INDUSTRY TRADE" },
  { symbol: "EGEEN", name: "EGE INDUSTRY AND TRADE" },
  { symbol: "ECILC", name: "ECZACIBASI PHARMACEUTICAL AND INDUSTRIAL INVESTMENT" },
  { symbol: "EKGYO", name: "EMLAK KONUT REAL ESTATE INVESTMENT TRUST" },
  { symbol: "ENJSA", name: "ENERJISA ENERGY" },
  { symbol: "ENERY", name: "ENERYA ENERGY" },
  { symbol: "ENKAI", name: "ENKA CONSTRUCTION AND INDUSTRY" },
  { symbol: "EREGL", name: "EREGLI IRON AND STEEL WORKS" },
  { symbol: "EUPWR", name: "EUROPOWER ENERGY AND AUTOMATION TECHNOLOGIES" },
  { symbol: "FENER", name: "FENERBAHCE FOOTBALL" },
  { symbol: "FROTO", name: "FORD AUTOMOTIVE INDUSTRY" },
  { symbol: "GSRAY", name: "GALATASARAY SPORTIVE INDUSTRIAL AND COMMERCIAL INVESTMENTS" },
  { symbol: "GENIL", name: "GEN PHARMACEUTICALS AND HEALTH PRODUCTS" },
  { symbol: "GESAN", name: "GIRISIM ELECTRIC INDUSTRY" },
  { symbol: "GRTHO", name: "GRAINTURK HOLDING" },
  { symbol: "GUBRF", name: "GUBRE FACTORIES" },
  { symbol: "GLRMK", name: "GULERMAK HEAVY INDUSTRY CONSTRUCTION AND CONTRACTING" },
  { symbol: "GRSEL", name: "GUR-SEL TOURISM TRANSPORTATION AND SERVICE TRADE" },
  { symbol: "SAHOL", name: "HACI OMER SABANCI HOLDING" },
  { symbol: "HEKTS", name: "HEKTAS TRADE" },
  { symbol: "ISDMR", name: "ISKENDERUN IRON AND STEEL" },
  { symbol: "ISMEN", name: "IS INVESTMENT SECURITIES" },
  { symbol: "IZENR", name: "IZDEMIR ENERGY ELECTRICITY PRODUCTION" },
  { symbol: "KRDMD", name: "KARDEMIR KARABUK IRON STEEL INDUSTRY AND TRADE" },
  { symbol: "KTLEV", name: "KATILIMEVIM SAVINGS FINANCING" },
  { symbol: "KLRHO", name: "KILER HOLDING" },
  { symbol: "KCAER", name: "KOCAER STEEL INDUSTRY AND TRADE" },
  { symbol: "KCHOL", name: "KOC HOLDING" },
  { symbol: "KONTR", name: "KONTROLMATIK TECHNOLOGY ENERGY AND ENGINEERING" },
  { symbol: "KUYAS", name: "KUYAS INVESTMENT" },
  { symbol: "MAGEN", name: "MARGUN ENERGY PRODUCTION INDUSTRY AND TRADE" },
  { symbol: "MAVI", name: "MAVI CLOTHING INDUSTRY AND TRADE" },
  { symbol: "MIATK", name: "MIA TECHNOLOGY" },
  { symbol: "MGROS", name: "MIGROS TRADE" },
  { symbol: "MPARK", name: "MLP HEALTHCARE SERVICES" },
  { symbol: "OBAMS", name: "OBA MACARONI INDUSTRY AND TRADE" },
  { symbol: "ODAS", name: "ODAS ELECTRICITY PRODUCTION INDUSTRY TRADE" },
  { symbol: "OTKAR", name: "OTOKAR AUTOMOTIVE AND DEFENSE INDUSTRY" },
  { symbol: "OYAKC", name: "OYAK CEMENT FACTORIES" },
  { symbol: "PASEU", name: "PASIFIK EURASIA LOGISTICS FOREIGN TRADE" },
  { symbol: "PATEK", name: "PASIFIK TECHNOLOGY" },
  { symbol: "PGSUS", name: "PEGASUS AIRLINES" },
  { symbol: "PETKM", name: "PETKIM PETROCHEMICAL HOLDING" },
  { symbol: "QUAGR", name: "QUA GRANITE DREAM BUILDING AND PRODUCTS" },
  { symbol: "RALYH", name: "RAL INVESTMENT HOLDING" },
  { symbol: "REEDR", name: "REEDER TECHNOLOGY INDUSTRY AND TRADE" },
  { symbol: "SASA", name: "SASA POLYESTER INDUSTRY" },
  { symbol: "SKBNK", name: "SEKERBANK" },
  { symbol: "SOKM", name: "SOK MARKETS TRADE" },
  { symbol: "TABGD", name: "TAB FOOD INDUSTRY AND TRADE" },
  { symbol: "TAVHL", name: "TAV AIRPORTS HOLDING" },
  { symbol: "TKFEN", name: "TEKFEN HOLDING" },
  { symbol: "TOASO", name: "TOFAS TURK AUTOMOBILE FACTORY" },
  { symbol: "TSPOR", name: "TRABZONSPOR SPORTIVE INVESTMENT AND FOOTBALL OPERATIONS" },
  { symbol: "TRMET", name: "TR ANATOLIA METAL MINING ENTERPRISES" },
  { symbol: "TRENJ", name: "TR NATURAL ENERGY RESOURCES RESEARCH AND PRODUCTION" },
  { symbol: "TUKAS", name: "TUKAS FOOD INDUSTRY AND TRADE" },
  { symbol: "TUREX", name: "TUREKS TOURISM TRANSPORTATION" },
  { symbol: "TCELL", name: "TURKCELL COMMUNICATION SERVICES" },
  { symbol: "TUPRS", name: "TUPRAS-TURKEY PETROLEUM REFINERIES" },
  { symbol: "TRALT", name: "TURK GOLD ENTERPRISES" },
  { symbol: "THYAO", name: "TURKISH AIRLINES" },
  { symbol: "GARAN", name: "GUARANTEE BANK OF TURKEY" },
  { symbol: "HALKB", name: "PEOPLES BANK OF TURKEY" },
  { symbol: "ISCTR", name: "ISBANK OF TURKEY" },
  { symbol: "TSKB", name: "INDUSTRIAL DEVELOPMENT BANK OF TURKEY" },
  { symbol: "TURSG", name: "TURKEY INSURANCE" },
  { symbol: "SISE", name: "TURKEY GLASS AND BOTTLE FACTORIES" },
  { symbol: "VAKBN", name: "VAKIFBANK OF TURKEY" },
  { symbol: "TTKOM", name: "TURK TELEKOM" },
  { symbol: "TTRAK", name: "TURK TRACTOR AND AGRICULTURAL MACHINERY" },
  { symbol: "ULKER", name: "ULKER BISCUIT INDUSTRY" },
  { symbol: "VESTL", name: "VESTEL ELECTRONICS INDUSTRY AND TRADE" },
  { symbol: "YKBNK", name: "YAPI KREDI BANK" },
  { symbol: "YEOTK", name: "YEO TECHNOLOGY ENERGY AND INDUSTRY" },
  { symbol: "ZOREN", name: "ZORLU ENERGY ELECTRICITY PRODUCTION" },
];

const TR_NAME_OVERRIDES: Record<string, string> = {
  AGHOL: "AG Anadolu Grubu Holding",
  AEFES: "Anadolu Efes Biracilik ve Malt Sanayi",
  AKSA: "Aksa Akrilik Kimya Sanayii",
  AKSEN: "Aksa Enerji Uretim",
  AKBNK: "Akbank",
  ALARK: "Alarko Holding",
  ALTNY: "Altinay Savunma Teknolojileri",
  ANSGR: "Anadolu Sigorta",
  ARCLK: "Arcelik",
  ASELS: "Aselsan Elektronik Sanayi ve Ticaret",
  ASTOR: "Astor Enerji",
  BALSU: "Balsu Gida Sanayi ve Ticaret",
  BTCIM: "Baticim Bati Anadolu Cimento Sanayii",
  BSOKE: "Batisoke Soke Cimento Sanayii",
  BIMAS: "BIM Birlesik Magazalar",
  BRSAN: "Borusan Mannesmann Boru",
  BRYAT: "Borusan Yatirim ve Pazarlama",
  CCOLA: "Coca-Cola Icecek",
  CANTE: "Can2 Termik",
  CIMSA: "Cimsa Cimento Sanayi ve Ticaret",
  CWENE: "CW Enerji Muhendislik Ticaret ve Sanayi",
  DOAS: "Dogus Otomotiv Servis ve Ticaret",
  DOHOL: "Dogan Sirketler Grubu Holding",
  DSTKF: "Destek Finans Faktoring",
  ECILC: "Eczacibasi Ilac Sanayi ve Finansal Yatirimlar",
  EFOR: "Efor Cay Sanayi Ticaret",
  EGEEN: "Ege Endustri ve Ticaret",
  EKGYO: "Emlak Konut GYO",
  ENJSA: "Enerjisa Enerji",
  ENERY: "Enerya Enerji",
  ENKAI: "Enka Insaat ve Sanayi",
  EREGL: "Eregli Demir ve Celik",
  EUPWR: "Europower Enerji ve Otomasyon Teknolojileri",
  FENER: "Fenerbahce Futbol",
  FROTO: "Ford Otomotiv Sanayi",
  GENIL: "Gen Ilac ve Saglik Urunleri",
  GESAN: "Girisim Elektrik Sanayi",
  GLRMK: "Gulermak Agir Sanayi Insaat ve Taahhut",
  GRSEL: "Gur-Sel Turizm Tasimacilik ve Servis Ticaret",
  GSRAY: "Galatasaray Sportif Sinai ve Ticari Yatirimlar",
  GRTHO: "Grainturk Holding",
  GUBRF: "Gubre Fabrikalari",
  HALKB: "Turkiye Halk Bankasi",
  HEKTS: "Hektas Ticaret",
  ISDMR: "Iskenderun Demir ve Celik",
  ISMEN: "Is Yatirim Menkul Degerler",
  ISCTR: "Turkiye Is Bankasi",
  IZENR: "Izdemir Enerji Elektrik Uretim",
  KCAER: "Kocaer Celik Sanayi ve Ticaret",
  KLRHO: "Kiler Holding",
  KCHOL: "Koc Holding",
  KONTR: "Kontrolmatik Teknoloji Enerji ve Muhendislik",
  KRDMD: "Kardemir Karabuk Demir Celik Sanayi ve Ticaret",
  KTLEV: "Katilimevim Tasarruf Finansman",
  KUYAS: "Kuyas Yatirim",
  MAGEN: "Margun Enerji Uretim Sanayi ve Ticaret",
  MAVI: "Mavi Giyim Sanayi ve Ticaret",
  MIATK: "Mia Teknoloji",
  MGROS: "Migros Ticaret",
  MPARK: "MLP Saglik Hizmetleri",
  OBAMS: "Oba Makarna Sanayi ve Ticaret",
  ODAS: "Odas Elektrik Uretim Sanayi Ticaret",
  OTKAR: "Otokar",
  OYAKC: "Oyak Cimento Fabrikalari",
  PASEU: "Pasifik Eurasia Lojistik Dis Ticaret",
  PATEK: "Pasifik Teknoloji",
  PGSUS: "Pegasus Hava Tasimaciligi",
  PETKM: "Petkim Petrokimya Holding",
  QUAGR: "Qua Granite Hayal Yapi ve Urunleri",
  RALYH: "Ral Yatirim Holding",
  REEDR: "Reeder Teknoloji Sanayi ve Ticaret",
  SASA: "Sasa Polyester Sanayi",
  SAHOL: "Haci Omer Sabanci Holding",
  SKBNK: "Sekerbank",
  SISE: "Turkiye Sise ve Cam Fabrikalari",
  SOKM: "Sok Marketler Ticaret",
  TABGD: "TAB Gida Sanayi ve Ticaret",
  TAVHL: "TAV Havalimanlari Holding",
  TKFEN: "Tekfen Holding",
  TCELL: "Turkcell Iletisim Hizmetleri",
  THYAO: "Turk Hava Yollari",
  TOASO: "Tofas Turk Otomobil Fabrikasi",
  TRALT: "Turk Altin Isletmeleri",
  TRENJ: "TR Dogal Enerji Kaynaklari Arastirma ve Uretim",
  TRMET: "TR Anadolu Metal Madencilik Isletmeleri",
  TSPOR: "Trabzonspor Sportif Yatirim ve Futbol Isletmeciligi",
  TTRAK: "Turk Traktor ve Ziraat Makineleri",
  TUKAS: "Tukas Gida Sanayi ve Ticaret",
  TUREX: "Tureks Turizm Tasimacilik",
  TURSG: "Turkiye Sigorta",
  TSKB: "Turkiye Sinai Kalkinma Bankasi",
  TTKOM: "Turk Telekom",
  TUPRS: "Tupras Turkiye Petrol Rafinerileri",
  ULKER: "Ulker Biskuvi",
  VAKBN: "Turkiye Vakiflar Bankasi",
  VESTL: "Vestel Elektronik Sanayi ve Ticaret",
  YKBNK: "Yapi ve Kredi Bankasi",
  YEOTK: "YEO Teknoloji Enerji ve Endustri",
  ZOREN: "Zorlu Enerji Elektrik Uretim",
};

const GENERIC_TR_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bCOMMUNICATION SERVICES\b/g, "ILETISIM HIZMETLERI"],
  [/\bELECTRICITY PRODUCTION\b/g, "ELEKTRIK URETIM"],
  [/\bENERGY PRODUCTION\b/g, "ENERJI URETIM"],
  [/\bENERGY\b/g, "ENERJI"],
  [/\bDEFENSE\b/g, "SAVUNMA"],
  [/\bTECHNOLOGIES\b/g, "TEKNOLOJILERI"],
  [/\bTECHNOLOGY\b/g, "TEKNOLOJI"],
  [/\bINDUSTRIAL\b/g, "ENDUSTRIYEL"],
  [/\bINDUSTRY\b/g, "SANAYI"],
  [/\bTRADE\b/g, "TICARET"],
  [/\bINVESTMENT\b/g, "YATIRIM"],
  [/\bHOLDING\b/g, "HOLDING"],
  [/\bCONSTRUCTION\b/g, "INSAAT"],
  [/\bAUTOMOTIVE\b/g, "OTOMOTIV"],
  [/\bHEALTHCARE\b/g, "SAGLIK"],
  [/\bPHARMACEUTICAL\b/g, "ILAC"],
  [/\bSERVICES\b/g, "HIZMETLERI"],
  [/\bGROUP\b/g, "GRUP"],
  [/\bBANK OF TURKEY\b/g, "TURKIYE BANKASI"],
  [/\bBANK\b/g, "BANKASI"],
  [/\bTURKEY\b/g, "TURKIYE"],
  [/\bAND\b/g, "VE"],
  [/\b\s+\b/g, " "],
];

const TOKEN_STOP_WORDS = new Set([
  "ve",
  "ile",
  "the",
  "and",
  "anonim",
  "sirketi",
  "sanayi",
  "ticaret",
  "holding",
  "bankasi",
  "bank",
  "industry",
  "trade",
  "services",
  "service",
  "investment",
  "investments",
  "group",
  "inc",
  "corp",
  "co",
]);

function toTurkishApproxName(nameEn: string): string {
  let translated = nameEn.toUpperCase();
  for (const [pattern, replacement] of GENERIC_TR_REPLACEMENTS) {
    translated = translated.replace(pattern, replacement);
  }

  return translated.replace(/\s+/g, " ").trim();
}

function splitTokens(value: string): string[] {
  return value
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .map((token) => token.trim())
    .filter((token) => token.length > 2 && !TOKEN_STOP_WORDS.has(token));
}

function buildAliases(symbol: string, nameEn: string, nameTr: string): string[] {
  const candidateTokens = [...splitTokens(nameEn), ...splitTokens(nameTr)];
  return Array.from(new Set([symbol, symbol.replace(".IS", ""), nameEn, nameTr, ...candidateTokens]));
}

export const BIST100_COMPANIES: BistCompany[] = RAW_BIST100_COMPANIES.map((company) => {
  const nameEn = company.name.trim();
  const nameTr = TR_NAME_OVERRIDES[company.symbol] ?? toTurkishApproxName(nameEn);
  const logoUrl = `${BIST_LOGO_BASE_URL}/${company.symbol}.png`;

  return {
    symbol: company.symbol,
    name: nameEn,
    nameEn,
    nameTr,
    officialNameTr: nameTr,
    aliases: buildAliases(company.symbol, nameEn, nameTr),
    logoUrl,
  };
});
