export type RssFeedSource = {
  id: string;
  name: string;
  language: "tr" | "en";
  url: string;
  priority: number;
};

export const DEFAULT_RSS_FEEDS: RssFeedSource[] = [
  {
    id: "bloomberght-ekonomi",
    name: "Bloomberg HT - Ekonomi",
    language: "tr",
    url: "https://www.bloomberght.com/rss",
    priority: 1,
  },
  {
    id: "ntv-ekonomi",
    name: "NTV - Ekonomi",
    language: "tr",
    url: "https://www.ntv.com.tr/ekonomi.rss",
    priority: 2,
  },
  {
    id: "dunya-ekonomi",
    name: "Dunya - Ekonomi",
    language: "tr",
    url: "https://www.dunya.com/rss",
    priority: 3,
  },
  {
    id: "hurriyet-ekonomi",
    name: "Hurriyet - Ekonomi",
    language: "tr",
    url: "https://www.hurriyet.com.tr/rss/ekonomi",
    priority: 4,
  },
  {
    id: "haberturk-ekonomi",
    name: "Haberturk - Ekonomi",
    language: "tr",
    url: "https://www.haberturk.com/rss/ekonomi.xml",
    priority: 5,
  },
  {
    id: "trthaber-ekonomi",
    name: "TRT Haber - Ekonomi",
    language: "tr",
    url: "https://www.trthaber.com/xml_mobile.php?tur=xml_genel&kategori=ekonomi",
    priority: 6,
  },
  {
    id: "ekonomim-gundem",
    name: "Ekonomim - Gundem",
    language: "tr",
    url: "https://www.ekonomim.com/rss",
    priority: 7,
  },
  {
    id: "anadoluajansi-ekonomi",
    name: "Anadolu Ajansi - Ekonomi",
    language: "tr",
    url: "https://www.aa.com.tr/tr/rss/default?cat=ekonomi",
    priority: 8,
  },
  {
    id: "milliyet-ekonomi",
    name: "Milliyet - Ekonomi",
    language: "tr",
    url: "https://www.milliyet.com.tr/rss/rssnew/ekonomi.xml",
    priority: 9,
  },
  {
    id: "sozcu-ekonomi",
    name: "Sozcu - Ekonomi",
    language: "tr",
    url: "https://www.sozcu.com.tr/rss/ekonomi.xml",
    priority: 10,
  },
  {
    id: "sabah-ekonomi",
    name: "Sabah - Ekonomi",
    language: "tr",
    url: "https://www.sabah.com.tr/rss/ekonomi.xml",
    priority: 11,
  },
  {
    id: "cumhuriyet-ekonomi",
    name: "Cumhuriyet - Ekonomi",
    language: "tr",
    url: "https://www.cumhuriyet.com.tr/rss/ekonomi.xml",
    priority: 12,
  },
  {
    id: "bigpara-ekonomi",
    name: "Bigpara - Ekonomi",
    language: "tr",
    url: "https://bigpara.hurriyet.com.tr/rss/",
    priority: 13,
  },
  {
    id: "trinvesting-ekonomi",
    name: "Investing TR - Ekonomi",
    language: "tr",
    url: "https://tr.investing.com/rss/news_25.rss",
    priority: 14,
  },
  {
    id: "ensonhaber-ekonomi",
    name: "Ensonhaber - Ekonomi",
    language: "tr",
    url: "https://www.ensonhaber.com/rss/ekonomi.xml",
    priority: 15,
  },
  {
    id: "haber7-ekonomi",
    name: "Haber7 - Ekonomi",
    language: "tr",
    url: "https://www.haber7.com/rss/ekonomi.xml",
    priority: 16,
  },
  {
    id: "t24-ekonomi",
    name: "T24 - Ekonomi",
    language: "tr",
    url: "https://t24.com.tr/rss",
    priority: 17,
  },
  {
    id: "ekonomist-ekonomi",
    name: "Ekonomist - Ekonomi",
    language: "tr",
    url: "https://www.ekonomist.com.tr/rss.xml",
    priority: 18,
  },
  {
    id: "capital-ekonomi",
    name: "Capital - Ekonomi",
    language: "tr",
    url: "https://www.capital.com.tr/rss.xml",
    priority: 19,
  },
  {
    id: "turkiyegazetesi-ekonomi",
    name: "Türkiye Gazetesi - Ekonomi",
    language: "tr",
    url: "https://www.turkiyegazetesi.com.tr/rss/ekonomi.xml",
    priority: 20,
  },
  {
    id: "yenisafak-ekonomi",
    name: "Yeni Şafak - Ekonomi",
    language: "tr",
    url: "https://www.yenisafak.com/rss/ekonomi.xml",
    priority: 21,
  },
  {
    id: "star-ekonomi",
    name: "Star - Ekonomi",
    language: "tr",
    url: "https://www.star.com.tr/rss/ekonomi.xml",
    priority: 22,
  },
  {
    id: "aksam-ekonomi",
    name: "Akşam - Ekonomi",
    language: "tr",
    url: "https://www.aksam.com.tr/rss/ekonomi.xml",
    priority: 23,
  },
  {
    id: "postacom-ekonomi",
    name: "Posta - Ekonomi",
    language: "tr",
    url: "https://www.posta.com.tr/rss/ekonomi.xml",
    priority: 24,
  },
  {
    id: "turkgun-ekonomi",
    name: "Türkgün - Ekonomi",
    language: "tr",
    url: "https://www.turkgun.com/rss/ekonomi.xml",
    priority: 25,
  },
  {
    id: "karar-ekonomi",
    name: "Karar - Ekonomi",
    language: "tr",
    url: "https://www.karar.com/rss/ekonomi.xml",
    priority: 26,
  },
  {
    id: "paradersgisi-ekonomi",
    name: "Para Dergisi - Ekonomi",
    language: "tr",
    url: "https://www.paradersgisi.com.tr/rss.xml",
    priority: 27,
  },
  {
    id: "borsagundem-ekonomi",
    name: "Borsa Gündem - Ekonomi",
    language: "tr",
    url: "https://www.borsagundem.com/rss.xml",
    priority: 28,
  },
  {
    id: "uzmanpara-ekonomi",
    name: "Uzmanpara - Ekonomi",
    language: "tr",
    url: "https://uzmanpara.milliyet.com.tr/rss/",
    priority: 29,
  },
  {
    id: "finansgundem-ekonomi",
    name: "Finans Gündem - Ekonomi",
    language: "tr",
    url: "https://www.finansgundem.com/rss.xml",
    priority: 30,
  },
  {
    id: "doviz-ekonomi",
    name: "Doviz.com - Ekonomi",
    language: "tr",
    url: "https://www.doviz.com/rss",
    priority: 31,
  },
  {
    id: "altin-ekonomi",
    name: "Altın.in - Ekonomi",
    language: "tr",
    url: "https://altin.in/rss.xml",
    priority: 32,
  },
  {
    id: "ekonomihaberleri-ekonomi",
    name: "Ekonomi Haberleri - Ekonomi",
    language: "tr",
    url: "https://www.ekonomihaberleri.com/rss.xml",
    priority: 33,
  },
  {
    id: "turkiyesigorta-ekonomi",
    name: "Türkiye Sigorta - Ekonomi",
    language: "tr",
    url: "https://www.turkiyesigorta.com.tr/rss.xml",
    priority: 34,
  },
  {
    id: "kobiden-ekonomi",
    name: "Kobiden - Ekonomi",
    language: "tr",
    url: "https://www.kobiden.com/rss.xml",
    priority: 35,
  },
  {
    id: "ticaret-ekonomi",
    name: "Ticaret - Ekonomi",
    language: "tr",
    url: "https://www.ticaret.gov.tr/rss",
    priority: 36,
  },
  {
    id: "turkstat-ekonomi",
    name: "TÜİK - Ekonomi",
    language: "tr",
    url: "https://www.tuik.gov.tr/rss/anasayfa.xml",
    priority: 37,
  },
  {
    id: "tcmb-ekonomi",
    name: "TCMB - Basın",
    language: "tr",
    url: "https://www.tcmb.gov.tr/rss/basin.xml",
    priority: 38,
  },
  {
    id: "bbc-business",
    name: "BBC - Business",
    language: "en",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    priority: 99,
  },
  {
    id: "cnbc-business",
    name: "CNBC - Business",
    language: "en",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10001147",
    priority: 100,
  },
  {
    id: "reuters-business",
    name: "Reuters - Business",
    language: "en",
    url: "https://feeds.reuters.com/reuters/businessNews",
    priority: 101,
  },
  {
    id: "reuters-world",
    name: "Reuters - World News",
    language: "en",
    url: "https://feeds.reuters.com/reuters/worldNews",
    priority: 102,
  },
  {
    id: "wsj-markets",
    name: "WSJ - Markets",
    language: "en",
    url: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    priority: 103,
  },
  {
    id: "wsj-business",
    name: "WSJ - Business",
    language: "en",
    url: "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    priority: 104,
  },
  {
    id: "marketwatch-topstories",
    name: "MarketWatch - Top Stories",
    language: "en",
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    priority: 105,
  },
  {
    id: "marketwatch-marketpulse",
    name: "MarketWatch - Market Pulse",
    language: "en",
    url: "https://feeds.content.dowjones.io/public/rss/mw_marketpulse",
    priority: 106,
  },
  {
    id: "investing-news",
    name: "Investing.com - Market News",
    language: "en",
    url: "https://www.investing.com/rss/news_25.rss",
    priority: 107,
  },
  {
    id: "yahoo-finance-news",
    name: "Yahoo Finance - News",
    language: "en",
    url: "https://finance.yahoo.com/news/rssindex",
    priority: 108,
  },
  {
    id: "ft-markets",
    name: "Financial Times - Markets",
    language: "en",
    url: "https://www.ft.com/markets?format=rss",
    priority: 109,
  },
  {
    id: "ft-companies",
    name: "Financial Times - Companies",
    language: "en",
    url: "https://www.ft.com/companies?format=rss",
    priority: 110,
  },
  {
    id: "seekingalpha-market",
    name: "Seeking Alpha - Market Currents",
    language: "en",
    url: "https://seekingalpha.com/market_currents.xml",
    priority: 111,
  },
  {
    id: "businessinsider-markets",
    name: "Business Insider - Markets",
    language: "en",
    url: "https://markets.businessinsider.com/rss/news",
    priority: 112,
  },
  {
    id: "federalreserve-press",
    name: "Federal Reserve - Press Releases",
    language: "en",
    url: "https://www.federalreserve.gov/feeds/press_all.xml",
    priority: 113,
  },
  {
    id: "imf-news",
    name: "IMF - News",
    language: "en",
    url: "https://www.imf.org/en/News/RSS",
    priority: 114,
  },
  {
    id: "oecd-economy",
    name: "OECD - Economy",
    language: "en",
    url: "https://www.oecd.org/economy/rss.xml",
    priority: 115,
  },
  {
    id: "nytimes-business",
    name: "NYTimes - Business",
    language: "en",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    priority: 116,
  },
  {
    id: "guardian-business",
    name: "The Guardian - Business",
    language: "en",
    url: "https://www.theguardian.com/business/rss",
    priority: 117,
  },
  {
    id: "worldbank-news",
    name: "World Bank - News",
    language: "en",
    url: "https://www.worldbank.org/en/news/all?output=rss",
    priority: 118,
  },
  {
    id: "ecb-press",
    name: "ECB - Press",
    language: "en",
    url: "https://www.ecb.europa.eu/rss/press.html",
    priority: 119,
  },
  {
    id: "ecb-podcast",
    name: "ECB - Podcast",
    language: "en",
    url: "https://www.ecb.europa.eu/rss/podcast.html",
    priority: 120,
  },
  {
    id: "fxstreet-news",
    name: "FXStreet - Forex News",
    language: "en",
    url: "https://www.fxstreet.com/rss/news",
    priority: 121,
  }
];
