import { writeFileSync } from "node:fs";

const data = `export type BistCompany = {
  symbol: string;
  name: string;
};

export const BIST100_COMPANIES: BistCompany[] = [
  { symbol: "AGHOL", name: "AG ANADOLU GROUP HOLDING" },
  { symbol: "AKBNK", name: "AKBANK" },
  { symbol: "AKSA", name: "AKSA ACRYLIC CHEMICAL INDUSTRY" },
  { symbol: "AKSEN", name: "AKSA ENERGY PRODUCTION" },
  { symbol: "ALARK", name: "ALARKO HOLDING" },
  { symbol: "ALTNY", name: "ALTINAY DEFENSE TECHNOLOGIES" },
  { symbol: "ANSGR", name: "ANADOLU INSURANCE COMPANY" },
  { symbol: "AEFES", name: "ANADOLU EFES BREWERY AND MALT INDUSTRY" },
  { symbol: "ARCLK", name: "ARCELIK" },
  { symbol: "ASELS", name: "ASELSAN ELECTRONICS INDUSTRY AND TRADE" },
  { symbol: "ASTOR", name: "ASTOR ENERGY" },
  { symbol: "BALSU", name: "BALSU FOOD INDUSTRY AND TRADE" },
  { symbol: "BTCIM", name: "BATICIM WEST ANATOLIA CEMENT INDUSTRY" },
  { symbol: "BSOKE", name: "BATISOKE SOKE CIMENTO INDUSTRY" },
  { symbol: "BIMAS", name: "BIM UNITED STORES" },
  { symbol: "BRSAN", name: "BORUSAN MANNESMANN PIPE INC." },
  { symbol: "BRYAT", name: "BORUSAN INVESTMENT AND MARKETING" },
  { symbol: "CCOLA", name: "COCA-COLA ICECEK" },
  { symbol: "CWENE", name: "CW ENERGY ENGINEERING TRADE AND INDUSTRY" },
  { symbol: "CANTE", name: "CAN2 THERMAL" },
  { symbol: "CIMSA", name: "CIMSA CEMENT INDUSTRY AND TRADE" },
  { symbol: "DOHOL", name: "DOGAN GROUP OF COMPANIES HOLDING" },
  { symbol: "DOAS", name: "DOGUS AUTOMOTIVE SERVICE AND TRADE" },
  { symbol: "DSTKF", name: "DESTEK FINANS FACTORING" },
  { symbol: "EFOR", name: "EFOR INVESTMENT INDUSTRY TRADE" },
  { symbol: "EGEEN", name: "EGE INDUSTRY AND TRADE" },
  { symbol: "ECILC", name: "ECZACIBASI PHARMACEUTICAL AND INDUSTRIAL INVESTMENT" },
  { symbol: "EKGYO", name: "EMLAK KONUT REAL ESTATE INVESTMENT TRUST" },
  { symbol: "ENJSA", name: "ENERJISA ENERGY" },
  { symbol: "ENERY", name: "ENERYA ENERGY" },
  { symbol: "ENKAI", name: "ENKA CONSTRUCTION AND INDUSTRY" },
  { symbol: "EREGL", name: "EREGLI IRON AND STEEL WORKS" },
  { symbol: "EUPWR", name: "EUROPOWER ENERGY AND AUTOMATION TECHNOLOGIES" },
  { symbol: "FENER", name: "FENERBAHCE FOOTBALL" },
  { symbol: "FROTO", name: "FORD AUTOMOTIVE INDUSTRY" },
  { symbol: "GSRAY", name: "GALATASARAY SPORTIVE INDUSTRIAL AND COMMERCIAL INVESTMENTS" },
  { symbol: "GENIL", name: "GEN PHARMACEUTICALS AND HEALTH PRODUCTS" },
  { symbol: "GESAN", name: "GIRISIM ELECTRIC INDUSTRY" },
  { symbol: "GRTHO", name: "GRAINTURK HOLDING" },
  { symbol: "GUBRF", name: "GUBRE FACTORIES" },
  { symbol: "GLRMK", name: "GULERMAK HEAVY INDUSTRY CONSTRUCTION AND CONTRACTING" },
  { symbol: "GRSEL", name: "GUR-SEL TOURISM TRANSPORTATION AND SERVICE TRADE" },
  { symbol: "SAHOL", name: "HACI OMER SABANCI HOLDING" },
  { symbol: "HEKTS", name: "HEKTAS TRADE" },
  { symbol: "ISDMR", name: "ISKENDERUN IRON AND STEEL" },
  { symbol: "ISMEN", name: "IS INVESTMENT SECURITIES" },
  { symbol: "IZENR", name: "IZDEMIR ENERGY ELECTRICITY PRODUCTION" },
  { symbol: "KRDMD", name: "KARDEMIR KARABUK IRON STEEL INDUSTRY AND TRADE" },
  { symbol: "KTLEV", name: "KATILIMEVIM SAVINGS FINANCING" },
  { symbol: "KLRHO", name: "KILER HOLDING" },
  { symbol: "KCAER", name: "KOCAER STEEL INDUSTRY AND TRADE" },
  { symbol: "KCHOL", name: "KOC HOLDING" },
  { symbol: "KONTR", name: "KONTROLMATIK TECHNOLOGY ENERGY AND ENGINEERING" },
  { symbol: "KUYAS", name: "KUYAS INVESTMENT" },
  { symbol: "MAGEN", name: "MARGUN ENERGY PRODUCTION INDUSTRY AND TRADE" },
  { symbol: "MAVI", name: "MAVI CLOTHING INDUSTRY AND TRADE" },
  { symbol: "MIATK", name: "MIA TECHNOLOGY" },
  { symbol: "MGROS", name: "MIGROS TRADE" },
  { symbol: "MPARK", name: "MLP HEALTHCARE SERVICES" },
  { symbol: "OBAMS", name: "OBA MACARONI INDUSTRY AND TRADE" },
  { symbol: "ODAS", name: "ODAS ELECTRICITY PRODUCTION INDUSTRY TRADE" },
  { symbol: "OTKAR", name: "OTOKAR AUTOMOTIVE AND DEFENSE INDUSTRY" },
  { symbol: "OYAKC", name: "OYAK CEMENT FACTORIES" },
  { symbol: "PASEU", name: "PASIFIK EURASIA LOGISTICS FOREIGN TRADE" },
  { symbol: "PATEK", name: "PASIFIK TECHNOLOGY" },
  { symbol: "PGSUS", name: "PEGASUS AIRLINES" },
  { symbol: "PETKM", name: "PETKIM PETROCHEMICAL HOLDING" },
  { symbol: "QUAGR", name: "QUA GRANITE DREAM BUILDING AND PRODUCTS" },
  { symbol: "RALYH", name: "RAL INVESTMENT HOLDING" },
  { symbol: "REEDR", name: "REEDER TECHNOLOGY INDUSTRY AND TRADE" },
  { symbol: "SASA", name: "SASA POLYESTER INDUSTRY" },
  { symbol: "SKBNK", name: "SEKERBANK" },
  { symbol: "SOKM", name: "SOK MARKETS TRADE" },
  { symbol: "TABGD", name: "TAB FOOD INDUSTRY AND TRADE" },
  { symbol: "TAVHL", name: "TAV AIRPORTS HOLDING" },
  { symbol: "TKFEN", name: "TEKFEN HOLDING" },
  { symbol: "TOASO", name: "TOFAS TURK AUTOMOBILE FACTORY" },
  { symbol: "TSPOR", name: "TRABZONSPOR SPORTIVE INVESTMENT AND FOOTBALL OPERATIONS" },
  { symbol: "TRMET", name: "TR ANATOLIA METAL MINING ENTERPRISES" },
  { symbol: "TRENJ", name: "TR NATURAL ENERGY RESOURCES RESEARCH AND PRODUCTION" },
  { symbol: "TUKAS", name: "TUKAS FOOD INDUSTRY AND TRADE" },
  { symbol: "TUREX", name: "TUREKS TOURISM TRANSPORTATION" },
  { symbol: "TCELL", name: "TURKCELL COMMUNICATION SERVICES" },
  { symbol: "TUPRS", name: "TUPRAS-TURKEY PETROLEUM REFINERIES" },
  { symbol: "TRALT", name: "TURK GOLD ENTERPRISES" },
  { symbol: "THYAO", name: "TURKISH AIRLINES" },
  { symbol: "GARAN", name: "GUARANTEE BANK OF TURKEY" },
  { symbol: "HALKB", name: "PEOPLES BANK OF TURKEY" },
  { symbol: "ISCTR", name: "ISBANK OF TURKEY" },
  { symbol: "TSKB", name: "INDUSTRIAL DEVELOPMENT BANK OF TURKEY" },
  { symbol: "TURSG", name: "TURKEY INSURANCE" },
  { symbol: "SISE", name: "TURKEY GLASS AND BOTTLE FACTORIES" },
  { symbol: "VAKBN", name: "VAKIFBANK OF TURKEY" },
  { symbol: "TTKOM", name: "TURK TELEKOM" },
  { symbol: "TTRAK", name: "TURK TRACTOR AND AGRICULTURAL MACHINERY" },
  { symbol: "ULKER", name: "ULKER BISCUIT INDUSTRY" },
  { symbol: "VESTL", name: "VESTEL ELECTRONICS INDUSTRY AND TRADE" },
  { symbol: "YKBNK", name: "YAPI KREDI BANK" },
  { symbol: "YEOTK", name: "YEO TECHNOLOGY ENERGY AND INDUSTRY" },
  { symbol: "ZOREN", name: "ZORLU ENERGY ELECTRICITY PRODUCTION" },
];
`;

writeFileSync("src/lib/bist100.ts", data);
